// ignore_for_file: constant_identifier_names
//
// Single source of truth for every icon used across the app.
// Call sites keep the old Material names (e.g. `AppIcons.home_rounded`) so a
// blanket `Icons.` → `AppIcons.` rename is safe, while the glyph comes from
// Phosphor for one consistent outline family. Filled glyphs are kept for
// status marks (check, warning, error, info) and selected navigation only.

import 'package:flutter/widgets.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

class AppIcons {
  AppIcons._();

  // ── Navigation / chrome ───────────────────────────────────────────────────
  static const IconData home_rounded = PhosphorIconsRegular.house;
  static const IconData home_outlined = PhosphorIconsRegular.house;
  static const IconData menu_rounded = PhosphorIconsRegular.list;
  static const IconData close = PhosphorIconsRegular.x;
  static const IconData close_rounded = PhosphorIconsRegular.x;
  static const IconData cancel = PhosphorIconsFill.xCircle;
  static const IconData cancel_rounded = PhosphorIconsFill.xCircle;
  static const IconData highlight_off_rounded = PhosphorIconsRegular.xCircle;
  static const IconData block_rounded = PhosphorIconsRegular.prohibit;
  static const IconData arrow_back = PhosphorIconsRegular.arrowLeft;
  static const IconData arrow_back_rounded = PhosphorIconsRegular.arrowLeft;
  static const IconData arrow_back_ios_new_rounded = PhosphorIconsRegular.caretLeft;
  static const IconData arrow_forward_ios_rounded = PhosphorIconsRegular.caretRight;
  static const IconData chevron_right = PhosphorIconsRegular.caretRight;
  static const IconData chevron_right_rounded = PhosphorIconsRegular.caretRight;
  static const IconData keyboard_arrow_down_rounded = PhosphorIconsRegular.caretDown;
  static const IconData keyboard_arrow_up_rounded = PhosphorIconsRegular.caretUp;
  static const IconData expand_more_rounded = PhosphorIconsRegular.caretDown;
  static const IconData check_rounded = PhosphorIconsRegular.check;
  static const IconData open_in_new = PhosphorIconsRegular.arrowSquareOut;
  static const IconData open_in_new_rounded = PhosphorIconsRegular.arrowSquareOut;
  static const IconData add = PhosphorIconsRegular.plus;
  static const IconData refresh = PhosphorIconsRegular.arrowClockwise;
  static const IconData refresh_rounded = PhosphorIconsRegular.arrowClockwise;
  static const IconData search_rounded = PhosphorIconsRegular.magnifyingGlass;
  static const IconData tune_rounded = PhosphorIconsRegular.slidersHorizontal;
  static const IconData tune_outlined = PhosphorIconsRegular.slidersHorizontal;
  static const IconData swap_horiz_rounded = PhosphorIconsRegular.arrowsLeftRight;
  static const IconData swap_vert_rounded = PhosphorIconsRegular.arrowsDownUp;

  // ── Status / feedback ─────────────────────────────────────────────────────
  static const IconData check_circle = PhosphorIconsFill.checkCircle;
  static const IconData check_circle_rounded = PhosphorIconsFill.checkCircle;
  static const IconData check_circle_outline = PhosphorIconsRegular.checkCircle;
  static const IconData check_circle_outline_rounded = PhosphorIconsRegular.checkCircle;
  static const IconData info_rounded = PhosphorIconsFill.info;
  static const IconData info_outline = PhosphorIconsRegular.info;
  static const IconData info_outline_rounded = PhosphorIconsRegular.info;
  static const IconData warning_rounded = PhosphorIconsFill.warning;
  static const IconData warning_amber_rounded = PhosphorIconsFill.warning;
  static const IconData error_outline = PhosphorIconsRegular.warningCircle;
  static const IconData error_outline_rounded = PhosphorIconsRegular.warningCircle;
  static const IconData report_problem_rounded = PhosphorIconsFill.warningOctagon;
  static const IconData report_problem_outlined = PhosphorIconsRegular.warningOctagon;
  static const IconData help_outline = PhosphorIconsRegular.question;
  static const IconData lightbulb_outline = PhosphorIconsRegular.lightbulb;
  static const IconData circle = PhosphorIconsFill.circle;
  static const IconData radio_button_checked = PhosphorIconsFill.circle;
  static const IconData radio_button_off = PhosphorIconsRegular.circle;

  // ── Auth / security ───────────────────────────────────────────────────────
  static const IconData lock_rounded = PhosphorIconsRegular.lock;
  static const IconData lock_outline = PhosphorIconsRegular.lock;
  static const IconData lock_outline_rounded = PhosphorIconsRegular.lock;
  static const IconData lock_reset_rounded = PhosphorIconsRegular.lockKey;
  static const IconData lock_reset_outlined = PhosphorIconsRegular.lockKey;
  static const IconData vpn_key_rounded = PhosphorIconsRegular.key;
  static const IconData password_rounded = PhosphorIconsRegular.password;
  static const IconData fingerprint_rounded = PhosphorIconsRegular.fingerprint;
  static const IconData fingerprint_outlined = PhosphorIconsRegular.fingerprint;
  static const IconData security_rounded = PhosphorIconsRegular.shieldCheck;
  static const IconData security_outlined = PhosphorIconsRegular.shieldCheck;
  static const IconData verified_rounded = PhosphorIconsFill.sealCheck;
  static const IconData verified_outlined = PhosphorIconsRegular.sealCheck;
  static const IconData verified_user_rounded = PhosphorIconsFill.shieldCheck;
  static const IconData visibility = PhosphorIconsRegular.eye;
  static const IconData visibility_rounded = PhosphorIconsRegular.eye;
  static const IconData visibility_off = PhosphorIconsRegular.eyeSlash;
  static const IconData visibility_off_rounded = PhosphorIconsRegular.eyeSlash;
  static const IconData logout_rounded = PhosphorIconsRegular.signOut;

  // ── Editing / actions ─────────────────────────────────────────────────────
  static const IconData edit_rounded = PhosphorIconsRegular.pencilSimple;
  static const IconData edit_note_rounded = PhosphorIconsRegular.notePencil;
  static const IconData save_rounded = PhosphorIconsRegular.floppyDisk;
  static const IconData send_rounded = PhosphorIconsRegular.paperPlaneTilt;
  static const IconData delete_outline_rounded = PhosphorIconsRegular.trash;
  static const IconData download_rounded = PhosphorIconsRegular.downloadSimple;
  static const IconData upload_file_rounded = PhosphorIconsRegular.uploadSimple;
  static const IconData share_rounded = PhosphorIconsRegular.shareNetwork;
  static const IconData link = PhosphorIconsRegular.link;
  static const IconData link_rounded = PhosphorIconsRegular.link;
  static const IconData language = PhosphorIconsRegular.globe;
  static const IconData add_comment_rounded = PhosphorIconsRegular.chatCircleText;

  // ── People / profile ──────────────────────────────────────────────────────
  static const IconData person = PhosphorIconsRegular.user;
  static const IconData person_rounded = PhosphorIconsRegular.user;
  static const IconData person_outline = PhosphorIconsRegular.user;
  static const IconData person_outline_rounded = PhosphorIconsRegular.user;
  static const IconData person_off_rounded = PhosphorIconsRegular.userMinus;
  static const IconData person_search_outlined = PhosphorIconsRegular.userFocus;
  static const IconData people_outline = PhosphorIconsRegular.users;
  static const IconData groups_rounded = PhosphorIconsRegular.users;
  static const IconData groups_outlined = PhosphorIconsRegular.users;
  static const IconData how_to_reg_rounded = PhosphorIconsRegular.userCheck;
  static const IconData how_to_reg_outlined = PhosphorIconsRegular.userCheck;
  static const IconData face_rounded = PhosphorIconsRegular.smiley;
  static const IconData man_rounded = PhosphorIconsRegular.user;
  static const IconData woman_rounded = PhosphorIconsRegular.user;
  static const IconData wc_rounded = PhosphorIconsRegular.genderIntersex;
  static const IconData family_restroom_rounded = PhosphorIconsRegular.usersFour;
  static const IconData family_restroom_outlined = PhosphorIconsRegular.usersFour;
  static const IconData badge_rounded = PhosphorIconsRegular.identificationBadge;
  static const IconData badge_outlined = PhosphorIconsRegular.identificationBadge;

  // ── Education / academic ──────────────────────────────────────────────────
  static const IconData school_rounded = PhosphorIconsRegular.graduationCap;
  static const IconData school_outlined = PhosphorIconsRegular.graduationCap;
  static const IconData menu_book = PhosphorIconsRegular.book;
  static const IconData menu_book_rounded = PhosphorIconsRegular.book;
  static const IconData menu_book_outlined = PhosphorIconsRegular.book;
  static const IconData library_books_rounded = PhosphorIconsRegular.books;
  static const IconData library_books_outlined = PhosphorIconsRegular.books;
  static const IconData local_library_rounded = PhosphorIconsRegular.books;
  static const IconData local_library_outlined = PhosphorIconsRegular.books;
  static const IconData cast_for_education_rounded = PhosphorIconsRegular.monitor;
  static const IconData cast_for_education_outlined = PhosphorIconsRegular.monitor;
  static const IconData history_edu_rounded = PhosphorIconsRegular.bookOpenText;
  static const IconData grade_rounded = PhosphorIconsFill.star;
  static const IconData grade_outlined = PhosphorIconsRegular.star;

  // ── Assignments / assessments ─────────────────────────────────────────────
  static const IconData assignment = PhosphorIconsRegular.clipboardText;
  static const IconData assignment_outlined = PhosphorIconsRegular.clipboardText;
  static const IconData assignment_rounded = PhosphorIconsRegular.clipboardText;
  static const IconData assignment_turned_in_rounded = PhosphorIconsRegular.checks;
  static const IconData assignment_turned_in_outlined = PhosphorIconsRegular.checks;
  static const IconData fact_check_rounded = PhosphorIconsRegular.checkSquare;
  static const IconData fact_check_outlined = PhosphorIconsRegular.checkSquare;
  static const IconData rule_folder_rounded = PhosphorIconsRegular.folderOpen;
  static const IconData quiz_rounded = PhosphorIconsRegular.question;
  static const IconData quiz_outlined = PhosphorIconsRegular.question;
  static const IconData assessment_outlined = PhosphorIconsRegular.chartBar;
  static const IconData playlist_add_check_rounded = PhosphorIconsRegular.checkSquare;
  static const IconData playlist_add_check_outlined = PhosphorIconsRegular.checkSquare;
  static const IconData playlist_add_check_circle_rounded = PhosphorIconsRegular.checkCircle;
  static const IconData playlist_add_check_circle_outlined = PhosphorIconsRegular.checkCircle;

  // ── Data / content ────────────────────────────────────────────────────────
  static const IconData article_rounded = PhosphorIconsRegular.article;
  static const IconData description_rounded = PhosphorIconsRegular.fileText;
  static const IconData description_outlined = PhosphorIconsRegular.fileText;
  static const IconData notes_rounded = PhosphorIconsRegular.notepad;
  static const IconData notes_outlined = PhosphorIconsRegular.notepad;
  static const IconData inventory_2_rounded = PhosphorIconsRegular.package;
  static const IconData summarize_rounded = PhosphorIconsRegular.listBullets;
  static const IconData table_chart_rounded = PhosphorIconsRegular.table;
  static const IconData insights_rounded = PhosphorIconsRegular.chartLineUp;
  static const IconData trending_up_rounded = PhosphorIconsRegular.trendUp;
  static const IconData track_changes_rounded = PhosphorIconsRegular.target;
  static const IconData track_changes_outlined = PhosphorIconsRegular.target;
  static const IconData timeline_rounded = PhosphorIconsRegular.chartLine;
  static const IconData history_rounded = PhosphorIconsRegular.clockCounterClockwise;
  static const IconData history_outlined = PhosphorIconsRegular.clockCounterClockwise;
  static const IconData folder = PhosphorIconsRegular.folder;
  static const IconData folder_rounded = PhosphorIconsRegular.folder;
  static const IconData folder_open_rounded = PhosphorIconsRegular.folderOpen;
  static const IconData folder_open_outlined = PhosphorIconsRegular.folderOpen;
  static const IconData insert_drive_file = PhosphorIconsRegular.file;
  static const IconData picture_as_pdf = PhosphorIconsRegular.filePdf;
  static const IconData video_file = PhosphorIconsRegular.fileVideo;

  // ── Communication ─────────────────────────────────────────────────────────
  static const IconData forum_rounded = PhosphorIconsRegular.chatsCircle;
  static const IconData forum_outlined = PhosphorIconsRegular.chatsCircle;
  static const IconData campaign = PhosphorIconsRegular.megaphone;
  static const IconData campaign_rounded = PhosphorIconsRegular.megaphone;
  static const IconData campaign_outlined = PhosphorIconsRegular.megaphone;
  static const IconData contact_mail_outlined = PhosphorIconsRegular.envelopeOpen;
  static const IconData email_outlined = PhosphorIconsRegular.envelope;
  static const IconData local_post_office_rounded = PhosphorIconsRegular.envelope;
  static const IconData call_outlined = PhosphorIconsRegular.phone;
  static const IconData phone_iphone_rounded = PhosphorIconsRegular.deviceMobile;
  static const IconData rate_review_rounded = PhosphorIconsRegular.chatCenteredText;
  static const IconData rate_review_outlined = PhosphorIconsRegular.chatCenteredText;
  static const IconData notifications_none_rounded = PhosphorIconsRegular.bell;

  // ── Finance ───────────────────────────────────────────────────────────────
  static const IconData paid_rounded = PhosphorIconsRegular.money;
  static const IconData payments_rounded = PhosphorIconsRegular.money;
  static const IconData payments_outlined = PhosphorIconsRegular.money;
  static const IconData account_balance_rounded = PhosphorIconsRegular.bank;
  static const IconData account_balance_wallet_rounded = PhosphorIconsRegular.wallet;
  static const IconData account_balance_wallet_outlined = PhosphorIconsRegular.wallet;
  static const IconData currency_exchange_rounded = PhosphorIconsRegular.currencyCircleDollar;
  static const IconData receipt_rounded = PhosphorIconsRegular.receipt;
  static const IconData receipt_outlined = PhosphorIconsRegular.receipt;
  static const IconData receipt_long_rounded = PhosphorIconsRegular.receipt;
  static const IconData receipt_long_outlined = PhosphorIconsRegular.receipt;
  static const IconData request_quote_rounded = PhosphorIconsRegular.fileText;
  static const IconData request_quote_outlined = PhosphorIconsRegular.fileText;

  // ── Calendar / time ───────────────────────────────────────────────────────
  static const IconData calendar_month_rounded = PhosphorIconsRegular.calendar;
  static const IconData calendar_month_outlined = PhosphorIconsRegular.calendar;
  static const IconData calendar_today_outlined = PhosphorIconsRegular.calendar;
  static const IconData calendar_today_rounded = PhosphorIconsRegular.calendar;
  static const IconData calendar_view_week_rounded = PhosphorIconsRegular.calendarBlank;
  static const IconData calendar_view_week_outlined = PhosphorIconsRegular.calendarBlank;
  static const IconData event_available_rounded = PhosphorIconsRegular.calendarCheck;
  static const IconData event_busy_rounded = PhosphorIconsRegular.calendarX;
  static const IconData today_rounded = PhosphorIconsRegular.calendarDot;
  static const IconData schedule = PhosphorIconsRegular.clock;
  static const IconData schedule_rounded = PhosphorIconsRegular.clock;
  static const IconData hourglass_empty_rounded = PhosphorIconsRegular.hourglass;
  static const IconData hourglass_top_rounded = PhosphorIconsRegular.hourglassHigh;
  static const IconData timelapse_rounded = PhosphorIconsRegular.timer;
  static const IconData pending_outlined = PhosphorIconsRegular.clockClockwise;

  // ── Location ──────────────────────────────────────────────────────────────
  static const IconData place_outlined = PhosphorIconsRegular.mapPin;
  static const IconData location_on_outlined = PhosphorIconsRegular.mapPin;
  static const IconData location_city_outlined = PhosphorIconsRegular.buildings;
  static const IconData map_outlined = PhosphorIconsRegular.mapTrifold;
  static const IconData wb_sunny_rounded = PhosphorIconsRegular.sun;
  static const IconData wb_sunny_outlined = PhosphorIconsRegular.sun;
  static const IconData room_rounded = PhosphorIconsRegular.door;
  static const IconData meeting_room_rounded = PhosphorIconsRegular.door;

  // ── QR / scanning ─────────────────────────────────────────────────────────
  static const IconData qr_code_rounded = PhosphorIconsRegular.qrCode;
  static const IconData qr_code_outlined = PhosphorIconsRegular.qrCode;
  static const IconData qr_code_2_rounded = PhosphorIconsRegular.qrCode;
  static const IconData qr_code_2_outlined = PhosphorIconsRegular.qrCode;
  static const IconData qr_code_scanner_rounded = PhosphorIconsRegular.scan;
  static const IconData flash_on_rounded = PhosphorIconsRegular.lightning;
  static const IconData flash_off_rounded = PhosphorIconsRegular.lightningSlash;
  static const IconData camera_alt_rounded = PhosphorIconsRegular.camera;
  static const IconData camera_alt_outlined = PhosphorIconsRegular.camera;
  static const IconData photo_library_rounded = PhosphorIconsRegular.imagesSquare;
  static const IconData broken_image_outlined = PhosphorIconsRegular.imageBroken;

  // ── Misc ──────────────────────────────────────────────────────────────────
  static const IconData play_arrow_rounded = PhosphorIconsRegular.play;
  static const IconData favorite_rounded = PhosphorIconsRegular.heart;
  static const IconData favorite_border_rounded = PhosphorIconsRegular.heart;
  static const IconData bookmark_rounded = PhosphorIconsRegular.bookmarkSimple;
  static const IconData inbox_rounded = PhosphorIconsRegular.tray;
  static const IconData inbox_outlined = PhosphorIconsRegular.tray;
  static const IconData confirmation_number_rounded = PhosphorIconsRegular.ticket;
  static const IconData local_activity_rounded = PhosphorIconsRegular.ticket;
  static const IconData construction_rounded = PhosphorIconsRegular.wrench;
  static const IconData construction_outlined = PhosphorIconsRegular.wrench;
  static const IconData work_outline_rounded = PhosphorIconsRegular.briefcase;
  static const IconData system_update_alt_rounded = PhosphorIconsRegular.arrowClockwise;
  static const IconData android_rounded = PhosphorIconsRegular.androidLogo;
  static const IconData cloud_sync_rounded = PhosphorIconsRegular.cloudArrowUp;
  static const IconData cloud_off_rounded = PhosphorIconsRegular.cloudSlash;
  static const IconData wifi_off_rounded = PhosphorIconsRegular.wifiSlash;

  // ── Added with the redesign: every Material name the screens use ─────────
  static const IconData account_balance_outlined = PhosphorIconsRegular.bank;
  static const IconData add_outlined = PhosphorIconsRegular.plus;
  static const IconData add_rounded = PhosphorIconsRegular.plus;
  static const IconData admin_panel_settings_outlined = PhosphorIconsRegular.userGear;
  static const IconData book_outlined = PhosphorIconsRegular.book;
  static const IconData business_outlined = PhosphorIconsRegular.buildings;
  static const IconData cake_outlined = PhosphorIconsRegular.cake;
  static const IconData cameraswitch_rounded = PhosphorIconsRegular.cameraRotate;
  static const IconData category_outlined = PhosphorIconsRegular.squaresFour;
  static const IconData chevron_left_rounded = PhosphorIconsRegular.caretLeft;
  static const IconData clear_rounded = PhosphorIconsRegular.x;
  static const IconData cloud_done_rounded = PhosphorIconsRegular.cloudCheck;
  static const IconData cloud_off = PhosphorIconsRegular.cloudSlash;
  static const IconData cloud_upload_outlined = PhosphorIconsRegular.cloudArrowUp;
  static const IconData cloud_upload_rounded = PhosphorIconsRegular.cloudArrowUp;
  static const IconData code_rounded = PhosphorIconsRegular.code;
  static const IconData dashboard = PhosphorIconsFill.squaresFour;
  static const IconData dashboard_outlined = PhosphorIconsRegular.squaresFour;
  static const IconData delete_sweep_outlined = PhosphorIconsRegular.trash;
  static const IconData edit_calendar_rounded = PhosphorIconsRegular.calendarDots;
  static const IconData edit_outlined = PhosphorIconsRegular.pencilSimple;
  static const IconData error_rounded = PhosphorIconsFill.warningCircle;
  static const IconData event_note_rounded = PhosphorIconsRegular.calendarDots;
  static const IconData event_outlined = PhosphorIconsRegular.calendarBlank;
  static const IconData event_rounded = PhosphorIconsRegular.calendarBlank;
  static const IconData favorite_outline_rounded = PhosphorIconsRegular.heart;
  static const IconData flashlight_on_rounded = PhosphorIconsRegular.flashlight;
  static const IconData grid_view_rounded = PhosphorIconsRegular.squaresFour;
  static const IconData group_add_outlined = PhosphorIconsRegular.userPlus;
  static const IconData group_outlined = PhosphorIconsRegular.users;
  static const IconData group_rounded = PhosphorIconsRegular.users;
  static const IconData help_outline_rounded = PhosphorIconsRegular.question;
  static const IconData hourglass_bottom_rounded = PhosphorIconsRegular.hourglassMedium;
  static const IconData image_outlined = PhosphorIconsRegular.image;
  static const IconData image_rounded = PhosphorIconsRegular.image;
  static const IconData inventory_2_outlined = PhosphorIconsRegular.package;
  static const IconData label_outline_rounded = PhosphorIconsRegular.tag;
  static const IconData lock_clock_rounded = PhosphorIconsRegular.clockCountdown;
  static const IconData lock_open_rounded = PhosphorIconsRegular.lockOpen;
  static const IconData login_rounded = PhosphorIconsRegular.signIn;
  static const IconData mail_outline_rounded = PhosphorIconsRegular.envelope;
  static const IconData manage_accounts_rounded = PhosphorIconsRegular.userGear;
  static const IconData manage_history_rounded = PhosphorIconsRegular.clockCounterClockwise;
  static const IconData nightlight_round = PhosphorIconsRegular.moon;
  static const IconData north_east_rounded = PhosphorIconsRegular.arrowUpRight;
  static const IconData notifications_outlined = PhosphorIconsRegular.bell;
  static const IconData offline_pin_rounded = PhosphorIconsRegular.cloudCheck;
  static const IconData people_outline_rounded = PhosphorIconsRegular.users;
  static const IconData person_add_rounded = PhosphorIconsRegular.userPlus;
  static const IconData phone_outlined = PhosphorIconsRegular.phone;
  static const IconData photo_camera_outlined = PhosphorIconsRegular.camera;
  static const IconData photo_library_outlined = PhosphorIconsRegular.images;
  static const IconData pie_chart_outline_rounded = PhosphorIconsRegular.chartPieSlice;
  static const IconData place_rounded = PhosphorIconsRegular.mapPin;
  static const IconData qr_code_2 = PhosphorIconsRegular.qrCode;
  static const IconData qr_code_scanner = PhosphorIconsRegular.scan;
  static const IconData qr_code_scanner_outlined = PhosphorIconsRegular.scan;
  static const IconData replay_rounded = PhosphorIconsRegular.arrowCounterClockwise;
  static const IconData sell_outlined = PhosphorIconsRegular.tag;
  static const IconData shield_outlined = PhosphorIconsRegular.shieldCheck;
  static const IconData source_outlined = PhosphorIconsRegular.folderSimple;
  static const IconData south_east_rounded = PhosphorIconsRegular.arrowDownRight;
  static const IconData stairs_outlined = PhosphorIconsRegular.stairs;
  static const IconData summarize_outlined = PhosphorIconsRegular.fileText;
  static const IconData sync = PhosphorIconsRegular.arrowsClockwise;
  static const IconData sync_problem = PhosphorIconsRegular.cloudWarning;
  static const IconData sync_rounded = PhosphorIconsRegular.arrowsClockwise;
  static const IconData tag_rounded = PhosphorIconsRegular.hash;
  static const IconData timer_off_rounded = PhosphorIconsRegular.timer;
  static const IconData timer_outlined = PhosphorIconsRegular.timer;
  static const IconData title_rounded = PhosphorIconsRegular.textT;
  static const IconData visibility_off_outlined = PhosphorIconsRegular.eyeSlash;
  static const IconData visibility_outlined = PhosphorIconsRegular.eye;
  static const IconData wb_twilight_rounded = PhosphorIconsRegular.sunHorizon;
  static const IconData wc_outlined = PhosphorIconsRegular.genderIntersex;
  static const IconData work_outlined = PhosphorIconsRegular.briefcase;

  // ── Redesign additions (not Material names) ──────────────────────────────
  static const IconData arrow_forward_rounded = PhosphorIconsRegular.arrowRight;
  static const IconData swap_school = PhosphorIconsRegular.arrowsLeftRight;
  static const IconData calendar_blank = PhosphorIconsRegular.calendarBlank;
  static const IconData map_pin = PhosphorIconsRegular.mapPin;
  static const IconData clock = PhosphorIconsRegular.clock;
  static const IconData users_three = PhosphorIconsRegular.usersThree;
  static const IconData scan = PhosphorIconsRegular.scan;
  static const IconData scan_fill = PhosphorIconsFill.scan;
  static const IconData house = PhosphorIconsRegular.house;
  static const IconData house_fill = PhosphorIconsFill.house;
  static const IconData squares_fill = PhosphorIconsFill.squaresFour;
  static const IconData calendar_fill = PhosphorIconsFill.calendarBlank;
  static const IconData qr_fill = PhosphorIconsFill.qrCode;
  static const IconData receipt_fill = PhosphorIconsFill.receipt;
  static const IconData megaphone = PhosphorIconsRegular.megaphone;
  static const IconData sign_out = PhosphorIconsRegular.signOut;
  static const IconData caret_up_down = PhosphorIconsRegular.caretUpDown;
  static const IconData dots_three = PhosphorIconsRegular.dotsThree;
  static const IconData id_card = PhosphorIconsRegular.identificationCard;
  static const IconData wallet = PhosphorIconsRegular.wallet;
  static const IconData chart_line_up = PhosphorIconsRegular.chartLineUp;
  static const IconData trend_up = PhosphorIconsRegular.trendUp;
  static const IconData user_circle = PhosphorIconsRegular.userCircle;
  static const IconData lock_key = PhosphorIconsRegular.lockKey;
  static const IconData camera = PhosphorIconsRegular.camera;
  static const IconData shield_check = PhosphorIconsRegular.shieldCheck;
  static const IconData info = PhosphorIconsRegular.info;
  static const IconData filter_list_rounded = PhosphorIconsRegular.funnelSimple;
  static const IconData menu = PhosphorIconsRegular.list;
}
