import 'package:flutter/material.dart';

import '../../../core/design/components/components.dart';
import '../../../core/design/tokens/app_tokens.dart';
import '../../../core/services/notification_service.dart';
import '../../../core/widgets/sync_status_banner.dart';

/// In-app notifications list. Shows sync results, offline-queue events,
/// and errors generated by the app. No push — purely local.
class NotificationsScreen extends StatefulWidget {
  const NotificationsScreen({super.key});

  @override
  State<NotificationsScreen> createState() => _NotificationsScreenState();
}

class _NotificationsScreenState extends State<NotificationsScreen> {
  List<AppNotification> _items = [];

  @override
  void initState() {
    super.initState();
    _items = NotificationService.instance.items;
    // Mark all as read on open.
    NotificationService.instance.markAllRead();
  }

  @override
  Widget build(BuildContext context) {
    return AppScaffold(
      titleWidget: const SizedBox.shrink(),
      actions: [
        if (_items.isNotEmpty)
          IconButton(
            tooltip: 'Clear all',
            icon: const Icon(Icons.delete_sweep_outlined),
            onPressed: () async {
              await NotificationService.instance.clear();
              if (!mounted) return;
              setState(() => _items = []);
            },
          ),
      ],
      body: Column(
        children: [
          const SyncStatusBanner(),
          Expanded(
            child: _items.isEmpty
                ? ListView(
                    children: const [
                      SizedBox(height: 120),
                      AppEmptyState(
                        icon: Icons.notifications_none_rounded,
                        title: 'No notifications',
                        subtitle:
                            'Sync results and app events will appear here.',
                      ),
                    ],
                  )
                : ListView.builder(
                    padding: const EdgeInsets.fromLTRB(16, 4, 16, 24),
                    itemCount: _items.length + 1,
                    itemBuilder: (context, i) {
                      if (i == 0) {
                        return AppPageHeader(
                          title: 'Notifications',
                          icon: Icons.notifications_outlined,
                          subtitle:
                              '${_items.length} event${_items.length == 1 ? '' : 's'}',
                        );
                      }
                      final n = _items[i - 1];
                      return _NotificationTile(notification: n);
                    },
                  ),
          ),
        ],
      ),
    );
  }
}

class _NotificationTile extends StatelessWidget {
  const _NotificationTile({required this.notification});
  final AppNotification notification;

  @override
  Widget build(BuildContext context) {
    final (icon, color) = _typeStyle(notification.type);
    return Padding(
      padding: const EdgeInsets.only(bottom: 10),
      child: AppCard(
        padding: const EdgeInsets.all(14),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              width: 40,
              height: 40,
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.10),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Icon(icon, color: color, size: 20),
            ),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    notification.title,
                    style: const TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w700,
                      color: AppInk.heading,
                    ),
                  ),
                  const SizedBox(height: 3),
                  Text(
                    notification.body,
                    style: const TextStyle(
                      fontSize: 12.5,
                      color: AppInk.body,
                      height: 1.4,
                    ),
                  ),
                  const SizedBox(height: 5),
                  Text(
                    _formatDate(notification.createdAt),
                    style: const TextStyle(
                      fontSize: 11.5,
                      fontWeight: FontWeight.w600,
                      color: AppInk.muted,
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  (IconData, Color) _typeStyle(String type) {
    switch (type) {
      case 'success':
        return (Icons.check_circle_rounded, AppInk.positive);
      case 'warning':
        return (Icons.warning_amber_rounded, AppInk.caution);
      case 'error':
        return (Icons.error_outline_rounded, AppInk.critical);
      case 'sync':
        return (Icons.sync_rounded, AppInk.accent);
      default:
        return (Icons.info_outline_rounded, AppInk.accent);
    }
  }

  String _formatDate(String iso) {
    try {
      final dt = DateTime.parse(iso);
      final now = DateTime.now();
      final diff = now.difference(dt);
      if (diff.inMinutes < 1) return 'Just now';
      if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
      if (diff.inHours < 24) return '${diff.inHours}h ago';
      if (diff.inDays < 7) return '${diff.inDays}d ago';
      return '${dt.year}-${dt.month.toString().padLeft(2, '0')}-${dt.day.toString().padLeft(2, '0')}';
    } catch (_) {
      return iso;
    }
  }
}
