<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>Receipt Verification — <?= htmlspecialchars(trim((string)($settings->SchoolName ?? 'FBMSO')), ENT_QUOTES, 'UTF-8'); ?></title>
<style>
	* { box-sizing: border-box; margin: 0; padding: 0; }
	body {
		font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
		background: #f1f5f9;
		color: #0f172a;
		min-height: 100vh;
		display: flex;
		align-items: center;
		justify-content: center;
		padding: 20px;
	}
	.card {
		background: #fff;
		border-radius: 16px;
		box-shadow: 0 10px 30px rgba(15, 23, 42, .08);
		max-width: 430px;
		width: 100%;
		overflow: hidden;
	}
	.card-head { padding: 20px 24px 0; text-align: center; }
	.school { font-size: .8rem; font-weight: 700; color: #64748b; letter-spacing: .04em; text-transform: uppercase; }
	.badge {
		display: inline-flex; align-items: center; gap: 8px;
		margin: 14px 0 4px; padding: 10px 18px;
		border-radius: 999px; font-weight: 800; font-size: .95rem;
	}
	.badge .dot { width: 10px; height: 10px; border-radius: 50%; background: currentColor; }
	.badge-ok    { background: #dcfce7; color: #166534; }
	.badge-void  { background: #fee2e2; color: #991b1b; }
	.badge-bad   { background: #e2e8f0; color: #475569; }
	.state-sub { font-size: .8rem; color: #64748b; padding-bottom: 16px; }
	.details { padding: 16px 24px 22px; border-top: 1px dashed #e2e8f0; }
	.row { display: flex; justify-content: space-between; gap: 14px; padding: 6px 0; font-size: .85rem; }
	.row .k { color: #64748b; font-weight: 600; }
	.row .v { text-align: right; font-weight: 600; word-break: break-word; }
	.items { border-top: 1px dashed #e2e8f0; margin-top: 10px; padding-top: 10px; }
	.total { border-top: 1px solid #0f172a; margin-top: 10px; padding-top: 10px; font-size: 1rem; font-weight: 800; }
	.foot { padding: 12px 24px 18px; font-size: .72rem; color: #94a3b8; text-align: center; }
</style>
</head>
<body>
<?php
	$studentName = '';
	$paidAt = '';
	if (!empty($payment)) {
		$lastName   = trim((string)($payment->LastName ?? ''));
		$firstName  = trim((string)($payment->FirstName ?? ''));
		$middleName = trim((string)($payment->MiddleName ?? ''));
		$studentName = trim(($lastName !== '' ? $lastName . ', ' : '') . $firstName . ($middleName !== '' ? ' ' . $middleName : ''));
		if ($studentName === '') {
			$studentName = trim((string)$payment->StudentNumber);
		}
		$paidAt = trim((string)($payment->PDate ?? ''));
		if ($paidAt !== '' && $paidAt !== '0000-00-00') {
			$paidAt = date('F d, Y', strtotime($paidAt));
			$pTime = trim((string)($payment->pTime ?? ''));
			if ($pTime !== '') {
				$paidAt .= ' ' . date('h:i A', strtotime($pTime));
			}
		}
	}
?>
	<div class="card">
		<div class="card-head">
			<div class="school"><?= htmlspecialchars(trim((string)($settings->SchoolName ?? 'FBMSO')), ENT_QUOTES, 'UTF-8'); ?></div>

			<?php if ($state === 'verified'): ?>
				<div class="badge badge-ok"><span class="dot"></span> OFFICIAL RECEIPT &mdash; VERIFIED</div>
				<div class="state-sub">This receipt exists in the system.</div>
			<?php elseif ($state === 'voided'): ?>
				<div class="badge badge-void"><span class="dot"></span> RECEIPT VOIDED</div>
				<div class="state-sub">This O.R. was reversed and no longer counts as payment.</div>
			<?php elseif ($state === 'not_found'): ?>
				<div class="badge badge-bad"><span class="dot"></span> NO MATCHING RECORD</div>
				<div class="state-sub">No receipt with this O.R. exists in the system.</div>
			<?php else: ?>
				<div class="badge badge-bad"><span class="dot"></span> INVALID VERIFICATION LINK</div>
				<div class="state-sub">This link is incomplete or was not generated by the system.</div>
			<?php endif; ?>
		</div>

		<?php if ($state === 'verified' || $state === 'voided'): ?>
		<div class="details">
			<div class="row"><span class="k">O.R. No.</span><span class="v"><?= htmlspecialchars((string)$or, ENT_QUOTES, 'UTF-8'); ?></span></div>
			<div class="row"><span class="k">Date</span><span class="v"><?= htmlspecialchars($paidAt, ENT_QUOTES, 'UTF-8'); ?></span></div>
			<div class="row"><span class="k">Received From</span><span class="v"><?= htmlspecialchars($studentName, ENT_QUOTES, 'UTF-8'); ?></span></div>
			<div class="row"><span class="k">Student No.</span><span class="v"><?= htmlspecialchars((string)($payment->StudentNumber ?? ''), ENT_QUOTES, 'UTF-8'); ?></span></div>
			<div class="row"><span class="k">Sem / SY</span><span class="v"><?= htmlspecialchars(trim((string)($payment->Sem ?? '') . ' ' . (string)($payment->SY ?? '')), ENT_QUOTES, 'UTF-8'); ?></span></div>
			<div class="row"><span class="k">Cashier</span><span class="v"><?= htmlspecialchars((string)($payment->Cashier ?? ''), ENT_QUOTES, 'UTF-8'); ?></span></div>

			<?php if (!empty($lines)): ?>
				<div class="items">
					<?php foreach ($lines as $line): ?>
						<div class="row">
							<span class="k" style="font-weight:500;"><?= htmlspecialchars((string)$line->description, ENT_QUOTES, 'UTF-8'); ?></span>
							<span class="v">&#8369; <?= number_format((float)$line->Amount, 2); ?></span>
						</div>
					<?php endforeach; ?>
				</div>
				<div class="row total"><span>TOTAL</span><span>&#8369; <?= number_format($total, 2); ?></span></div>
			<?php endif; ?>
		</div>
		<?php endif; ?>

		<div class="foot">
			Verified <?= date('F d, Y h:i A'); ?> &middot; This page only confirms whether the O.R. exists and is valid.
		</div>
	</div>
</body>
</html>
